require: rubocop-rake

AllCops:
  TargetRubyVersion: 2.4
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Exclude:
    - 'spec/**/*'

Gemspec/RequiredRubyVersion:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false
